

export const PROFILE_GET                         = 'PROFILE_GET';
export const PROFILE_GET_SUCCESS                 = 'PROFILE_GET_SUCCESS';
export const PROFILE_GET_FAILURE                 = 'PROFILE_GET_FAILURE';

export const PROFILE_CREATE_0                    = 'PROFILE_CREATE_0';
export const PROFILE_CREATE_SUCCESS_0            = 'PROFILE_CREATE_SUCCESS_0';
export const PROFILE_CREATE_FAILURE_0            = 'PROFILE_CREATE_FAILURE_0';
export const PROFILE_CREATE_INIT_0               = 'PROFILE_CREATE_INIT_0';

export const PROFILE_CREATE_1                    = 'PROFILE_CREATE_1';
export const PROFILE_CREATE_SUCCESS_1            = 'PROFILE_CREATE_SUCCESS_1';
export const PROFILE_CREATE_FAILURE_1            = 'PROFILE_CREATE_FAILURE_1';
export const PROFILE_CREATE_INIT_1               = 'PROFILE_CREATE_INIT_1';

export const PROFILE_GET_RATINGS                 = 'PROFILE_GET_RATINGS';
export const PROFILE_GET_RATINGS_SUCCESS         = 'PROFILE_GET_RATINGS_SUCCESS';
export const PROFILE_GET_RATINGS_FAILURE         = 'PROFILE_GET_RATINGS_FAILURE';

export const PROFILE_MOVIE_RATE                  = 'PROFILE_MOVIE_RATE';
export const PROFILE_MOVIE_RATE_SUCCESS          = 'PROFILE_MOVIE_RATE_SUCCESS';
export const PROFILE_MOVIE_RATE_FAILURE          = 'PROFILE_MOVIE_RATE_FAILURE';

export const PROFILE_MOVIE_DELETE_RATING         = 'PROFILE_MOVIE_DELETE_RATING';
export const PROFILE_MOVIE_DELETE_RATING_SUCCESS = 'PROFILE_MOVIE_DELETE_RATING_SUCCESS';
export const PROFILE_MOVIE_DELETE_RATING_FAILURE = 'PROFILE_MOVIE_DELETE_RATING_FAILURE';

export const PROFILE_GET_RECOMMENDATIONS         = 'PROFILE_GET_RECOMMENDATIONS';
export const PROFILE_GET_RECOMMENDATIONS_SUCCESS = 'PROFILE_GET_RECOMMENDATIONS_SUCCESS';
export const PROFILE_GET_RECOMMENDATIONS_FAILURE = 'PROFILE_GET_RECOMMENDATIONS_FAILURE';

// export const PROFILE_SET_MOVIE_STATE             = 'PROFILE_SET_MOVIE_STATE';
// export const PROFILE_SET_MOVIE_STATE_SUCCESS     = 'PROFILE_SET_MOVIE_STATE_SUCCESS';
// export const PROFILE_SET_MOVIE_STATE_FAILURE     = 'PROFILE_SET_MOVIE_STATE_FAILURE';
