
export const ACTION_DETAIL_CLEAR            = 'ACTION_DETAIL_CLEAR';

export const ACTION_DETAIL_GET_REQUEST      = 'ACTION_DETAIL_GET_REQUEST';
export const ACTION_DETAIL_GET_SUCCESS      = 'ACTION_DETAIL_GET_SUCCESS';
export const ACTION_DETAIL_GET_FAILURE      = 'ACTION_DETAIL_GET_FAILURE';

export const SET_ACTION_STATE               = 'SET_ACTION_STATE';
export const SET_ACTION_STATE_SUCCESS       = 'SET_ACTION_STATE_SUCCESS';
export const SET_ACTION_STATE_FAILURE       = 'SET_ACTION_STATE_FAILURE';

export const CREATE_NEW_ACTION              = 'CREATE_NEW_ACTION';
export const CREATE_NEW_ACTION_SUCCESS      = 'CREATE_NEW_ACTION_SUCCESS';
export const CREATE_NEW_ACTION_FAILURE      = 'CREATE_NEW_ACTION_FAILURE';

export const DELETE_ACTION                  = 'DELETE_ACTION';
export const DELETE_ACTION_SUCCESS          = 'DELETE_ACTION_SUCCESS';
export const DELETE_ACTION_FAILURE          = 'DELETE_ACTION_FAILURE';
